name: CI
on: [push]
jobs:
  build:
    runs-on: macos-15
    name: Build & Test
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Check Swift Version
        run: swift --version

      - name: Setup Racket
        uses: Bogdanp/setup-racket@v1.13
        with:
          variant: 'CS'
          version: 'current'
          packages: 'http-easy-lib'

      - name: Build LFS file list
        run: git lfs ls-files -l | cut -d ' ' -f1 | sort > .lfs-ids

      - name: Cache LFS files
        uses: actions/cache@v4
        with:
          path: .git/lfs
          key: lfs-${{ hashFiles('.lfs-ids') }}

      - name: Pull LFS
        run: git lfs pull

      - name: Install noise-serde-lib
        run:
          pushd Racket && raco pkg install --auto noise-serde-lib/ noise-serde-doc/

      - name: Build & Test
        run: make && swift build && swift test
